name: Atualizar Notícias Diário

on:
  schedule:
    - cron: "0 7 * * *"   # Atualiza todo dia às 7h
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install requests

      - name: Gerar notícias
        run: python gerar_noticias.py

      - name: Commit e Push das novas notícias
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add noticias.json
          git commit -m "Atualização automática de notícias"
          git push

